# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  front-end:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env: 
      REACT_APP_CLIENT_ID: 95d62e39e2a948b99b2b378d11a6e8c0,
      REACT_APP_AUTHORIZE_URL: https://accounts.spotify.com/authorize,
      REACT_APP_REDIRECT_URL: http://localhost:3000/home,
      REACT_APP_BACK_END_URI: http://localhost:5000
      CI: false
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - working-directory: ./front-end
      run: npm ci
    - working-directory: ./front-end
      run: npm install
    - working-directory: ./front-end
      run: npm run build --if-present
    - working-directory: ./front-end
      run: npm run serve-build
  back-end:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env: 
      BUILD_TEST: true
      FRONT_END_URI: http://localhost:3000,
      BACK_END_URI: http://localhost:5000
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - working-directory: ./back-end
      run: npm ci
    - working-directory: ./back-end
      run: npm install
    - working-directory: ./back-end
      run: npm start
    - working-directory: ./back-end
      run: npm test 
